CREATE USER PROIECT IDENTIFIED BY proiect 
DEFAULT TABLESPACE "USERS"
TEMPORARY TABLESPACE "TEMP";

CREATE ROLE dll_admin;

GRANT CREATE TABLE to dll_admin;

GRANT CREATE ANY INDEX to dll_admin;

GRANT CREATE ANY VIEW to dll_admin;

GRANT CREATE SESSION TO "PROIECT";

ALTER USER "PROIECT" DEFAULT ROLE "DLL_ADMIN";