apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    finalizers:
    - kubernetes.io/pvc-protection
    name: test-pvc
    namespace: default
spec: 
    accessModes:
    - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
    selector:
        matchLabels:
            type: test-pv
    storageClassName: ""
    volumeMode: Filesystem
    volumeName: test-pv


