apiVersion: v1
kind: PersistentVolume
metadata:
    finalizers:
    - kubernetes.io/pv-protection
    labels:
        type: test-pv 
    name: test-pv
spec:
    accessModes:
    - ReadWriteOnce
    capacity:
        storage: 5Gi
    claimRef:
        apiVersion: v1
        kind: PersistentVolumeClaim
        name: test-pvc
        namespace: default
    persistentVolumeReclaimPolicy: Retain
    volumeMode: Filesystem
    storageClassName: local-storage
    local:
      path: /tmp
    nodeAffinity:
      required:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - worker-node01
            - worker-node02
            - worker-node03