
name: Smoke tests
on:
  push:
    paths:
      - '.github/workflows/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
 test:
   if: "!contains(github.event.head_commit.message, '[ci skip]')"
   runs-on: [ ubuntu-latest ]
   permissions:
    contents: read
    packages: write

   steps:
   
     - name: Login to GitHub Container Registry
       uses: docker/login-action@v1
       with:
         registry: ghcr.io
         username: ${{ github.repository_owner }}
         p455w0rd: ${{ secrets.GITHUB_REGISTRY_TOKEN }}
         
     - name: Build and Push Docker Image
       uses: docker/build-push-action@v2
       with:
         push: true # Will only build if this is not here
         tags: |
           ghcr.io/${{ github.repository }}:${{ github.ref }}
           ghcr.io/${{ github.repository }}:latest







