
name: Smoke tests
on:
  push:
    paths:
      - '.github/workflows/**'

jobs:
 test:
   if: "!contains(github.event.head_commit.message, '[ci skip]')"
   runs-on: [ ubuntu-latest ]
   container:
    image: node:14.16
   permissions:
    contents: read
    packages: write

   steps:

     - name: Check for dockerenv file
       run: |
        echo "hello" > hello.txt
        cat hello.txt
        ls -lha








