name: Smoke tests
on:
  push:
    paths:
      - '.github/workflows/**'

jobs:
 test:
   runs-on: [ ubuntu-latest ]
   steps:
     - name: Run smoke tests
      #  if: contains(github.event.head_commit.message, 'smoke_test')
       if: "!contains(github.event.head_commit.message, 'ci skip')"
       run: |
         echo 'Running smoke tests!'

     - name: Run Bat
       run: |
        npm install -g bats
        bats -v
        sudo apt-get update
        # curl --silent --location --remote-name \
        # "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v3.2.3/kustomize_kustomize.v3.2.3_linux_amd64" && \
        # chmod a+x kustomize_kustomize.v3.2.3_linux_amd64 && \
        # sudo mv kustomize_kustomize.v3.2.3_linux_amd64 /usr/local/bin/kustomize && \
        # sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 && \
        # sudo chmod a+x /usr/local/bin/yq
        yq --version
        echo "yq installed successfully"




