name: Smoke tests
on:
  push:
    paths:
      - '.github/workflows/**'

jobs:
 test:
   runs-on: [ ubuntu-latest ]
   steps:
     - name: Run smoke tests
      #  if: contains(github.event.head_commit.message, 'smoke_test')
       if: "!contains(github.event.head_commit.message, 'ci skip')"
       run: |
         echo 'Running smoke tests!'

     - name: learn-github-actions
        run-name: ${{ github.actor }} is learning GitHub Actions
        jobs:
          check-bats-version:
            runs-on: ubuntu-latest
            steps:
              - uses: actions/checkout@v3
              - uses: actions/setup-node@v3
                with:
                  node-version: '14'
              - run: npm install -g bats
              - run: bats -v
              - run: sudo apt-get update
              - run: sudo apt-get install yq


