name: Smoke tests
on:
  push:
    paths:
      - '.github/workflows/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
 test:
   runs-on: [ ubuntu-latest ]
   permissions:
    contents: read
    packages: write

   steps:
     - name: Run smoke tests
      #  if: contains(github.event.head_commit.message, 'smoke_test')
       if: "!contains(github.event.head_commit.message, 'ci skip')"
       run: |
         echo 'Running smoke tests!'

     - name: Run Bat
       run: |
        npm install -g bats
        bats -v
        sudo apt-get update
        # curl --silent --location --remote-name \
        # "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize/v3.2.3/kustomize_kustomize.v3.2.3_linux_amd64" && \
        # chmod a+x kustomize_kustomize.v3.2.3_linux_amd64 && \
        # sudo mv kustomize_kustomize.v3.2.3_linux_amd64 /usr/local/bin/kustomize && \
        # sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 && \
        # sudo chmod a+x /usr/local/bin/yq
        # yq --version
        # echo "yq installed successfully"

     - name: Checkout repository
       uses: actions/checkout@v3

     - name: Log in to the Container registry
       uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
       with:
         registry: ${{ env.REGISTRY }}
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

     - name: Extract metadata (tags, labels) for Docker
       id: meta
       uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
       with:
         images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

     - name: Build and push Docker image
       uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
       with:
         context: .
         push: true
         tags: ${{ steps.meta.outputs.tags }}
         labels: ${{ steps.meta.outputs.labels }}







