on:
  push:
    branches:
    - master
Test1:
  - name: Build container image
    id: docker_build-push
    uses: docker/build-push-action@v2
    with:
      file: ./Dockerfile
      context: .
      push: true