name: Smoke tests
on:
  push:
    paths:
      - '.github/workflows/**'



jobs:
 test:
   runs-on: [ ubuntu-latest ]
   steps:
     - name: Run smoke tests
      #  if: contains(github.event.head_commit.message, 'smoke_test')
       if: "!contains(github.event.head_commit.message, 'ci skip')"
       run: |
         echo 'Running smoke tests!'


