
name: Smoke tests
on:
  push:
    paths:
      - '.github/workflows/**'

env:
  # REGISTRY: ghcr.io
  # IMAGE_NAME: ${{ github.repository }}

jobs:
 test:
   if: "!contains(github.event.head_commit.message, '[ci skip]')"
   runs-on: [ ubuntu-latest ]
   container:
    image: node:14.16
   permissions:
    contents: read
    packages: write

   steps:

     - name: Check for dockerenv file
       run: ls







